# Generated by Django 5.2.17 on 2026-09-01 03:16

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('api', 'API'), ('local', 'Local File'), ('mysql', 'MySQL')], max_length=20)),
                ('source_name', models.CharField(max_length=100)),
                ('source_ref', models.CharField(blank=True, max_length=500)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('raw_content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('restricted', 'Restricted')], default='internal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'raw_documents',
                'indexes': [models.Index(fields=['source_type', 'source_name'], name='raw_documen_source__d2c33d_idx'), models.Index(fields=['is_active'], name='raw_documen_is_acti_a5117b_idx')],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_name', 'external_id', 'version'), name='uniq_source_version')],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024)),
                ('embedding_model', models.CharField(default='bge-m3', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ingestion.rawdocument')),
            ],
            options={
                'db_table': 'document_chunks',
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw_idx', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('raw_document', 'chunk_index'), name='uniq_chunk_per_doc')],
            },
        ),
    ]
